# Generated by Django 3.1.4 on 2021-03-23 10:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diagnoses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='updated_on',
            field=models.DateField(default=datetime.datetime(2021, 3, 23, 10, 43, 9, 582004, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
