# Generated by Django 3.1.4 on 2021-03-23 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_auto_20210323_2231'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
        ('diagnoses', '0002_diagnosis_updated_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='pid',
            new_name='patient',
        ),
        migrations.AlterUniqueTogether(
            name='diagnosis',
            unique_together={('patient', 'title')},
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('json', models.JSONField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('updated_on', models.DateField()),
                ('created_on', models.DateField()),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='investigation_created_by', to=settings.AUTH_USER_MODEL)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='diagnoses.diagnosis', verbose_name='Diagnosis')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_investigation', to='templates.investigation', verbose_name='Template')),
            ],
            options={
                'verbose_name_plural': 'Investigations',
                'ordering': ['-updated_on', 'created_on'],
                'unique_together': {('diagnosis', 'template')},
            },
        ),
    ]
