# Generated by Django 3.1.4 on 2021-03-23 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigation',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='tags',
        ),
        migrations.AddField(
            model_name='investigation',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 3, 23, 11, 31, 31, 539092, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investigation',
            name='updated_on',
            field=models.DateField(default=datetime.datetime(2021, 3, 23, 11, 31, 40, 676887, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
