# Generated by Django 3.1.4 on 2021-01-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='template_json',
            new_name='json',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='template_tags',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='template',
            name='kind',
            field=models.CharField(choices=[('Issue', 'Issue'), ('Investigation', 'Investigation')], default='Issue', max_length=13),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='template',
            unique_together={('title', 'kind', 'json')},
        ),
    ]
