# Generated by Django 3.1.4 on 2021-01-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_auto_20210124_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
