# Generated by Django 3.1.4 on 2021-02-06 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('templates', '0004_template_hints'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='presentation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('json', models.JSONField()),
                ('tags', models.TextField(blank=True, null=True)),
                ('differential', models.TextField(blank=True, null=True)),
                ('presentation', models.TextField(blank=True, null=True)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issue_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Templates',
                'ordering': ['-name'],
                'unique_together': {('name', 'json')},
            },
        ),
    ]
