# Generated by Django 3.1.4 on 2021-02-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0005_auto_20210206_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-title'], 'verbose_name_plural': 'Issues'},
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('title', 'json')},
        ),
    ]
