# Generated by Django 3.1.4 on 2021-04-02 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('issue', 'Issue'), ('result', 'Result')], max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('json', models.JSONField()),
                ('updated_on', models.DateField()),
                ('created_on', models.DateField()),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schema_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Schemas',
                'ordering': ['-title'],
                'unique_together': {('title', 'kind', 'json')},
            },
        ),
    ]
