# Generated by Django 3.1.4 on 2021-04-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_auto_20210404_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
