# Generated by Django 3.1.4 on 2021-04-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0003_schema_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schema',
            options={'ordering': ['ordering'], 'verbose_name_plural': 'Schemas'},
        ),
        migrations.AlterField(
            model_name='schema',
            name='kind',
            field=models.CharField(choices=[('issue', 'Issue'), ('investigation', 'Investigation')], max_length=30),
        ),
    ]
