# Generated by Django 3.1.4 on 2021-03-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examination',
            old_name='pid',
            new_name='patient',
        ),
        migrations.AlterUniqueTogether(
            name='examination',
            unique_together={('patient', 'collected_on')},
        ),
    ]
