# Generated by Django 3.1.4 on 2021-01-19 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialHx',
            fields=[
                ('pid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='patients.patient', verbose_name='Patient')),
                ('living', models.CharField(blank=True, max_length=255, null=True, verbose_name='Living Arrangements')),
                ('working', models.CharField(blank=True, max_length=255, null=True, verbose_name='Working Arrangements')),
                ('smoking', models.CharField(blank=True, max_length=255, null=True, verbose_name='Smoking')),
                ('drinking', models.CharField(blank=True, max_length=255, null=True, verbose_name='Drinking')),
                ('children', models.CharField(blank=True, max_length=255, null=True, verbose_name='Children')),
                ('family', models.CharField(blank=True, max_length=255, null=True, verbose_name='Family')),
                ('template', models.TextField(default='\nlives {{living}}, children: {{children}}, {{working}}, smoking: {{smoking}}, alcohol: {{drinking}}, family hx: {{family}}, {{#if other}}other: {{other}}{{/if}}\n')),
                ('template_value', models.TextField()),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='socialhx_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Social Histories',
            },
        ),
    ]
