# Generated by Django 3.1.4 on 2021-02-25 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        ('templates', '0009_auto_20210214_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('pulse', models.CharField(blank=True, max_length=50, null=True)),
                ('BP', models.CharField(blank=True, max_length=8, null=True, verbose_name='Blood Pressure')),
                ('presentation', models.TextField(blank=True, null=True)),
                ('examination', models.TextField(blank=True, null=True)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField()),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_created_by', to=settings.AUTH_USER_MODEL)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_pid', to='patients.patient', verbose_name='Patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_consultations', to='doctors.providernumber', verbose_name='Provider')),
            ],
            options={
                'verbose_name_plural': 'Consultations',
                'ordering': ['-created_on'],
                'unique_together': {('pid', 'code', 'created_on')},
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('json', models.JSONField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('presentation', models.TextField(blank=True, null=True)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('updated_on', models.DateField()),
                ('created_on', models.DateField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='consultations.consultation', verbose_name='Consultation')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issue_created_by', to=settings.AUTH_USER_MODEL)),
                ('tid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_issue', to='templates.issue', verbose_name='Template')),
            ],
            options={
                'verbose_name_plural': 'Issues',
                'ordering': ['-updated_on', '-created_on'],
                'unique_together': {('cid', 'title', 'created_on')},
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10, verbose_name='Status')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('updated_on', models.DateField()),
                ('created_on', models.DateField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='consultations.consultation', verbose_name='Consultation')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='letters_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Letters',
                'ordering': ['-created_on'],
                'unique_together': {('cid', 'created_on')},
            },
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('json', models.JSONField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('updated_on', models.DateField()),
                ('created_on', models.DateField()),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='investigation_created_by', to=settings.AUTH_USER_MODEL)),
                ('iid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='consultations.issue', verbose_name='Issue')),
                ('tid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_investigation', to='templates.investigation', verbose_name='Template')),
            ],
            options={
                'verbose_name_plural': 'Investigations',
                'ordering': ['-title'],
                'unique_together': {('iid', 'title', 'created_on')},
            },
        ),
    ]
