# Generated by Django 3.1.4 on 2021-03-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='presentation',
            new_name='impression',
        ),
        migrations.RenameField(
            model_name='consultation',
            old_name='pid',
            new_name='patient',
        ),
        migrations.AddField(
            model_name='consultation',
            name='history',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultation',
            name='plan',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='consultation',
            unique_together={('patient', 'code', 'created_on')},
        ),
    ]
