# Generated by Django 3.1.4 on 2021-02-25 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnoses', '0001_initial'),
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='diagnosis',
            field=models.ForeignKey(default='bdf011f5-cff4-480f-abbd-d8c43984beda', on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_investigations', to='diagnoses.diagnosis', verbose_name='Diagnosis'),
            preserve_default=False,
        ),
    ]
