# Generated by Django 3.1.4 on 2021-03-02 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_consultation_diagnosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='diagnosis',
        ),
    ]
