# Generated by Django 3.1.4 on 2021-03-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_examination'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='sats_desc',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Saturation Description'),
        ),
    ]
