# Generated by Django 3.1.4 on 2021-03-02 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_remove_consultation_diagnosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigation',
            name='diagnosis',
        ),
    ]
