# Generated by Django 3.1.4 on 2021-03-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_remove_investigation_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
