# Generated by Django 3.1.4 on 2021-01-19 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimPaid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fname', models.CharField(help_text='First Name', max_length=50, verbose_name='First Name')),
                ('lname', models.CharField(help_text='Last Name', max_length=50, verbose_name='Last Name')),
                ('code', models.IntegerField()),
                ('amount', models.FloatField()),
                ('billed_on', models.DateField()),
                ('paid_on', models.DateField()),
                ('dob', models.DateField(blank=True, null=True)),
                ('billed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_paid_billed_by', to='doctors.providernumber')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='claim_paid_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Claims Paid',
                'ordering': ['-billed_on'],
                'unique_together': {('fname', 'lname', 'billed_on', 'billed_by')},
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50, verbose_name='First Name')),
                ('lname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('code', models.IntegerField()),
                ('amount', models.FloatField()),
                ('billed_on', models.DateField()),
                ('dob', models.DateField(blank=True, null=True)),
                ('billed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_billed_by', to='doctors.providernumber')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='claim_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-billed_on'],
                'unique_together': {('fname', 'lname', 'billed_on', 'billed_by')},
            },
        ),
    ]
